baseurl = "https://williamsorellana.cf/"
theme = "hugo_theme_pickles"
DefaultContentLanguage = "en"
pygmentStyle = "native"

[languages]
[languages.en]
weight = 1
Title = "Williams Orellana"
copyright = "&copy; Copyright 2018"
bio = "Software developer, passionate about Technology, Free Software, Python, Debian and Blender."
translations = "Translations"

[languages.es]
weight = 2
Title = "Williams Orellana"

copyright = "&copy; Derechos Reservados 2018"
bio = "Desarrollador de software, apasionado de la tecnología, el software libre, Python, Debian y Blender."
translations = "Traducciones"

[[languages.en.menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
[[languages.en.menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[[languages.es.menu.main]]
    name = "Blog"
    url = "/es"
    weight = 1
[[languages.es.menu.main]]
    name = "Acerca"
    url = "/es/acerca"
    weight = 2

[params]
  truncated = false
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "worellana"
  #facebook = "Your Facebook username"
  instagram = "williamsorellana"
  googleplus = "https://plus.google.com/+WilliamsOrellana" # https://plus.google.com/u/0/xxxxxx
  github = "worellana"
  gitlab = "worellana"
  #npm = "Your npm username"
  #codepen = "Your CodePen username"
  #dribbble = "Your Dribbble username"
  #fivehundredpx = "Your 500px username" # 500px
  #flickr = "Your Flickr username"
  #pinterest = "Your Pinterest username"
  #tumblr = "Your Tumblr username"
  #vimeo = "Your Vimeo username"
  #youtube = "Your YouTube username"
  linkedin = "williamsorellana"
  # Disqus shortname
  disqus = "williamsorellana"
  # Google Analytics API key.
  ga_api_key = "UA-84522060-1"
  author = "Williams Orellana"
  authorwebsite = "williamsorellana.cf"
  avatar = "https://es.gravatar.com/userimage/1565874/bc9b2b643022f10225def6a0873d5478.jpg?size=200"
#  contact = "/contact"
#  bio = "Software developer, passionate about Technology, Free Software, Python, Debian and Blender."
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "~/worellana/home"
  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "favicon.ico"

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2018"

[taxonomies]
   tag = "tags"
   category = "categories"